"""Regenerate <export root>/ASSETS.md from every <Asset>/manifest.json.  python -I make_index.py"""
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from config import ROOT  # noqa: E402

rows = []
for d in sorted(os.listdir(ROOT)):
    mp = f"{ROOT}/{d}/manifest.json"
    if not os.path.exists(mp):
        continue
    m = json.load(open(mp))
    slots = m.get("material_slots") or list(m["materials"])
    coll = m["collision"] if isinstance(m["collision"], list) else [m["collision"]]
    rows.append((d, m["asset"], m["size_cm_xyz"], m.get("triangles_approx", "?"), slots, len(coll), m.get("description", "")))

lines = ["# Asset index", "",
         "Generated by `Scripts/AssetPipeline/make_index.py` from each asset's `manifest.json`. Sizes are centimetres (X, Y, Z), origin at ground centre, Z up.",
         "Each `Preview.png` is rendered from the exported FBX + textures only (re-imported), so it shows what an import will contain.", "",
         f"{len(rows)} assets.", "",
         "| Asset | Mesh | Size cm | Tris | Material slots | Collision | What it is |", "|---|---|---|---|---|---|---|"]
for d, a, sz, tris, slots, nc, desc in rows:
    lines.append(f"| [{d}]({d}/Preview.png) | `{a}.fbx` | {sz[0]} x {sz[1]} x {sz[2]} | {tris} | {', '.join(slots)} | {nc} | {desc} |")
lines += ["", "Shared textures: `Library/Textures/T_Lib_<Key>_{BC,N,ORM}.png` (keys: see `TILED` in `lib.py`). Stone assets have their own baked",
          "`<Asset>/Textures/T_<Asset>_Stone_{BC,N,ORM}.png`. Plain materials are parameter-only (values in each manifest).",
          "Nothing here is imported into Unreal by this pipeline; see `Scripts/AssetPipeline/README.md`.", ""]
open(f"{ROOT}/ASSETS.md", "w", encoding="utf-8").write("\n".join(lines))
print(f"wrote {ROOT}/ASSETS.md ({len(rows)} assets)")
